import mediapipe as mp

mp_holistic = mp.solutions.holistic
CONFIANCE_INDEX = 0.5

#------------------------------Função de mapeamento da mão direita------------------------------------------
def map_right_hand(results, img_hight, img_width):
    # mao esquerda:
    hand_right_keypoints_2d = [
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.WRIST].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.WRIST].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_CMC].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_CMC].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_MCP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_IP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_IP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_TIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_MCP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_PIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_DIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_TIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_MCP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_PIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_DIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_TIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_MCP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_PIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_DIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_TIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_MCP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_PIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_DIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_TIP].x * img_width,
        results.right_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_TIP].y * img_hight,
        CONFIANCE_INDEX
    ]

    return hand_right_keypoints_2d

#--------------------------- Função de mapeamento da mão esquerda -----------------------------------------
def map_left_hand(results, img_hight, img_width):
    # mao esquerda:
    hand_left_keypoints_2d = [
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.WRIST].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.WRIST].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_CMC].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_CMC].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_MCP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_IP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_IP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_TIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.THUMB_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_MCP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_PIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_DIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_TIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.INDEX_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_MCP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_PIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_DIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_TIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.MIDDLE_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_MCP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_PIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_DIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_TIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.RING_FINGER_TIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_MCP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_MCP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_PIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_PIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_DIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_DIP].y * img_hight,
        CONFIANCE_INDEX,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_TIP].x * img_width,
        results.left_hand_landmarks.landmark[mp_holistic.HandLandmark.PINKY_TIP].y * img_hight,
        CONFIANCE_INDEX
    ]

    return hand_left_keypoints_2d

#--------------------------- Função de mapeamento da corpo -----------------------------------------
def map_pose(results, img_hight, img_width):

    point_one = {
        'x': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].x + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].x)/2,
        'y': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].y + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].y)/2,
        'visibility': (results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].visibility +  results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].visibility)/2
    }

    point_eight = {
        'x': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].x + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].x)/2,
        'y': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].y + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].y)/2,
        'visibility': (results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].visibility +  results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].visibility)/2
    }

    point_nineteen = {
        'x': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].x + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].x)/2,
        'y': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].y + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].y)/2,
        'visibility': (results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].visibility +  results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].visibility)/2
    }

    point_twenty_two = {
        'x': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].x + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].x)/2,
        'y': (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].y + results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].y)/2,
        'visibility': (results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].visibility +  results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].visibility)/2
    }
    
    
    pose_keypoints_2d = [
        #0
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].visibility,
        #1
        point_one['x'] * img_width,
        point_one['y'] * img_hight,
        point_one['visibility'],
        #2
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_SHOULDER].visibility,
        #3
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ELBOW].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ELBOW].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ELBOW].visibility,
        #4
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_WRIST].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_WRIST].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_WRIST].visibility,
        #5
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_SHOULDER].visibility,
        #6
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ELBOW].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ELBOW].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ELBOW].visibility,
        #7
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_WRIST].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_WRIST].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_WRIST].visibility,
        #8
        point_eight['x'] * img_width,
        point_eight['y'] * img_hight,
        point_eight['visibility'],
        #9
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HIP].visibility,
        #10
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_KNEE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_KNEE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_KNEE].visibility,
        #11
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ANKLE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ANKLE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_ANKLE].visibility,
        #12
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].visibility,
        #13
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_KNEE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_KNEE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_KNEE].visibility,
        #14
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ANKLE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ANKLE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ANKLE].visibility,
        #15
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EYE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EYE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EYE].visibility,
        #16
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EYE].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EYE].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EYE].visibility,
        #17
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EAR].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EAR].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_EAR].visibility,
        #18
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].visibility,
        #19
        point_nineteen['x'] * img_width,
        point_nineteen['y'] * img_hight,
        point_nineteen['visibility'],
        #20
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_FOOT_INDEX].visibility,
        #21
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HEEL].visibility,
        #22
        point_twenty_two['x'] * img_width,
        point_twenty_two['y'] * img_hight,
        point_twenty_two['visibility'],
        #23
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_FOOT_INDEX].visibility,
        #24
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].x * img_width,
        results.pose_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].y * img_hight,
        results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.RIGHT_HEEL].visibility,
    ]

    return pose_keypoints_2d

#------------------------------- Função de mapeamento da face -------------------------------------------
def map_face(results, img_hight, img_width):    
    face_keypoints_2d = [
        #contorno rosto
        results.face_landmarks.landmark[127].x * img_width,
        results.face_landmarks.landmark[127].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[234].x * img_width,
        results.face_landmarks.landmark[234].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[93].x * img_width,
        results.face_landmarks.landmark[93].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[132].x * img_width,
        results.face_landmarks.landmark[132].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[58].x * img_width,
        results.face_landmarks.landmark[58].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[172].x * img_width,
        results.face_landmarks.landmark[172].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[136].x * img_width,
        results.face_landmarks.landmark[136].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[176].x * img_width,
        results.face_landmarks.landmark[176].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[152].x * img_width,
        results.face_landmarks.landmark[152].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[400].x * img_width,
        results.face_landmarks.landmark[400].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[379].x * img_width,
        results.face_landmarks.landmark[379].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[397].x * img_width,
        results.face_landmarks.landmark[397].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[288].x * img_width,
        results.face_landmarks.landmark[288].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[361].x * img_width,
        results.face_landmarks.landmark[361].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[323].x * img_width,
        results.face_landmarks.landmark[323].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[454].x * img_width,
        results.face_landmarks.landmark[454].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[356].x * img_width,
        results.face_landmarks.landmark[356].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[70].x * img_width,
        results.face_landmarks.landmark[70].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[63].x * img_width,
        results.face_landmarks.landmark[63].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[105].x * img_width,
        results.face_landmarks.landmark[105].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[66].x * img_width,
        results.face_landmarks.landmark[66].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[107].x * img_width,
        results.face_landmarks.landmark[107].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[336].x * img_width,
        results.face_landmarks.landmark[336].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[296].x * img_width,
        results.face_landmarks.landmark[296].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[334].x * img_width,
        results.face_landmarks.landmark[334].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[293].x * img_width,
        results.face_landmarks.landmark[293].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[300].x * img_width,
        results.face_landmarks.landmark[300].y * img_hight,
        CONFIANCE_INDEX,
        #nariz
        results.face_landmarks.landmark[8].x * img_width,
        results.face_landmarks.landmark[8].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[168].x * img_width,
        results.face_landmarks.landmark[168].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[197].x * img_width,
        results.face_landmarks.landmark[197].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[4].x * img_width,
        results.face_landmarks.landmark[4].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[165].x * img_width,
        results.face_landmarks.landmark[165].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[167].x * img_width,
        results.face_landmarks.landmark[167].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[164].x * img_width,
        results.face_landmarks.landmark[164].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[393].x * img_width,
        results.face_landmarks.landmark[393].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[391].x * img_width,
        results.face_landmarks.landmark[391].y * img_hight,
        CONFIANCE_INDEX,
        #olhos
        results.face_landmarks.landmark[33].x * img_width,
        results.face_landmarks.landmark[33].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[160].x * img_width,
        results.face_landmarks.landmark[160].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[158].x * img_width,
        results.face_landmarks.landmark[158].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[133].x * img_width,
        results.face_landmarks.landmark[133].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[153].x * img_width,
        results.face_landmarks.landmark[153].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[144].x * img_width,
        results.face_landmarks.landmark[144].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[362].x * img_width,
        results.face_landmarks.landmark[362].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[385].x * img_width,
        results.face_landmarks.landmark[385].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[387].x * img_width,
        results.face_landmarks.landmark[387].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[263].x * img_width,
        results.face_landmarks.landmark[263].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[373].x * img_width,
        results.face_landmarks.landmark[373].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[380].x * img_width,
        results.face_landmarks.landmark[380].y * img_hight,
        CONFIANCE_INDEX,
        #boca
        results.face_landmarks.landmark[61].x * img_width,
        results.face_landmarks.landmark[61].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[40].x * img_width,
        results.face_landmarks.landmark[40].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[37].x * img_width,
        results.face_landmarks.landmark[37].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[0].x * img_width,
        results.face_landmarks.landmark[0].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[267].x * img_width,
        results.face_landmarks.landmark[267].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[270].x * img_width,
        results.face_landmarks.landmark[270].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[291].x * img_width,
        results.face_landmarks.landmark[291].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[321].x * img_width,
        results.face_landmarks.landmark[321].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[314].x * img_width,
        results.face_landmarks.landmark[314].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[17].x * img_width,
        results.face_landmarks.landmark[17].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[84].x * img_width,
        results.face_landmarks.landmark[84].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[181].x * img_width,
        results.face_landmarks.landmark[181].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[78].x * img_width,
        results.face_landmarks.landmark[78].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[82].x * img_width,
        results.face_landmarks.landmark[82].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[13].x * img_width,
        results.face_landmarks.landmark[13].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[312].x * img_width,
        results.face_landmarks.landmark[312].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[308].x * img_width,
        results.face_landmarks.landmark[308].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[317].x * img_width,
        results.face_landmarks.landmark[317].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[14].x * img_width,
        results.face_landmarks.landmark[14].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[87].x * img_width,
        results.face_landmarks.landmark[87].y * img_hight,
        CONFIANCE_INDEX,
        #iris
        results.face_landmarks.landmark[468].x * img_width,
        results.face_landmarks.landmark[468].y * img_hight,
        CONFIANCE_INDEX,
        results.face_landmarks.landmark[473].x * img_width,
        results.face_landmarks.landmark[473].y * img_hight,
        CONFIANCE_INDEX,
    ]

    return face_keypoints_2d